repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        types:
          - python

  - repo: local
    hooks:
      - id: license-header
        name: Code files must have a license header
        language: system
        entry: license-eye header fix
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint must pass
        language: system
        entry: make lint
        pass_filenames: false

      - id: go-mod-tidy
        name: run go mod tidy
        language: system
        entry: go mod tidy
        pass_filenames: false
