repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: license-header
        name: Code files must have a license header
        language: system
        entry: license-eye header fix
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint (tgm-collector) must pass
        language: system
        entry: bash -c 'cd tgm-collector && make lint'
        pass_filenames: false

      - id: go-mod-tidy
        name: run go mod tidy (tgm-collector)
        language: system
        entry: bash -c 'cd tgm-collector && go mod tidy'
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint (collector-framework) must pass
        language: system
        entry: bash -c 'cd collector-framework && make lint'
        pass_filenames: false

      - id: go-mod-tidy
        name: run go mod tidy (collector-framework)
        language: system
        entry: bash -c 'cd collector-framework && go mod tidy'
        pass_filenames: false
