FROM registry.access.redhat.com/ubi9 as builder


RUN dnf -y install git python3-pip gcc ncurses-devel

RUN pip3 install scons \
	&& git clone https://gitlab.com/gpsd/gpsd.git

WORKDIR /gpsd

RUN scons -c \
	&& scons install
	#&& scons udev-install


FROM registry.access.redhat.com/ubi9

RUN dnf -y install python3-pip

COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

#add ubxtool dependency when gpsd is not used
RUN pip3 install pyserial

#add gpsmon
COPY --from=builder /usr/local/bin/gpsmon /usr/local/bin/gpsmon

#add ubxtool
COPY --from=builder /usr/local/bin/ubxtool /usr/local/bin/ubxtool

#add gpsd
COPY --from=builder /usr/local/sbin/gpsd /usr/local/sbin/gpsd

COPY gpsd.sh /root/gpsd.sh

#run gpsd
ENTRYPOINT ["sh", "-c", "/root/gpsd.sh"]
