apiVersion: v1
kind: Pod
metadata:
  name: gnssutils
  namespace: openshift-ptp
spec:
  restartPolicy: Never
  volumes:
    - name: pts
      hostPath:
        path: /dev/pts
        type: Directory
  containers:
    - name: gpsd
      image: quay.io/jnunez/gnss-utils:3.25_dev
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: pts
          mountPath: /dev/pts
      env:
        - name: BUS
          value: "gnss0"
