FROM registry.access.redhat.com/ubi9 as builder


RUN dnf -y install python3-pip

RUN pip3 install allantools scipy pandas numpy matplotlib
COPY . /app

ENTRYPOINT ["python3", "/app/ptp_ngen_kpis.py"]
