value: testvalue
suite_configs:
  - tests.simple_config:
      target_latency: 120
      permitted_jitter: 3
    tests.complex_config:
      interface_name: en0
      target_ip: "8.8.8.8"
      latency:
        target_latency: 999
        permitted_jitter: 1
